---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: ubuntu-20.04-redis
    server_type: cx11
    image: ubuntu-20.04
lint: |
  flake8
provisioner:
  name: ansible
verifier:
  name: testinfra
