---
dependency:
  name: galaxy
driver:
  name: hetznercloud
lint:
  name: yamllint
  enabled: False
platforms:
  - name: ubuntu-20.04-redis
    server_type: cx11
    image: ubuntu-20.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
verifier:
  name: testinfra
  lint:
    name: flake8
    options:
      max-line-length: 120
