---
- name: Define redis_packages
  set_fact:
    redis_packages: "{{ __redis_packages }}"
  when: redis_packages is not defined

- name: Define redis_daemon
  set_fact:
    redis_daemon: "{{ __redis_daemon }}"
  when: redis_daemon is not defined

- name: Define redis_conf_path
  set_fact:
    redis_conf_path: "{{ __redis_conf_path }}"
  when: redis_conf_path is not defined

...
